//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPD {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IPD.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;root&gt;
        ///  &lt;connected&gt;
        ///    &lt;item&gt;
        ///      &lt;ip&gt;192.168.1.13&lt;/ip&gt;
        ///      &lt;port&gt;6000&lt;/port&gt;
        ///    &lt;/item&gt;
        ///  &lt;/connected&gt;
        ///&lt;/root&gt; 的本地化字符串。
        /// </summary>
        internal static string initConfig {
            get {
                return ResourceManager.GetString("initConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;a&gt;
        ///  &lt;e class=&quot;object&quot;&gt;
        ///    &lt;AxisSum type=&quot;number&quot;&gt;0&lt;/AxisSum&gt;
        ///    &lt;Name type=&quot;string&quot;&gt;无&lt;/Name&gt;
        ///    &lt;En type=&quot;string&quot;&gt;R_NULL&lt;/En&gt;
        ///    &lt;Num type=&quot;number&quot;&gt;0&lt;/Num&gt;
        ///  &lt;/e&gt;
        ///  &lt;e class=&quot;object&quot;&gt;
        ///    &lt;AxisSum type=&quot;number&quot;&gt;6&lt;/AxisSum&gt;
        ///    &lt;Name type=&quot;string&quot;&gt;六轴&lt;/Name&gt;
        ///    &lt;En type=&quot;string&quot;&gt;R_GENERAL_6S&lt;/En&gt;
        ///    &lt;Num type=&quot;number&quot;&gt;1&lt;/Num&gt;
        ///  &lt;/e&gt;
        ///  &lt;e class=&quot;object&quot;&gt;
        ///    &lt;AxisSum type=&quot;number&quot;&gt;4&lt;/AxisSum&gt;
        ///    &lt;Name type=&quot;string&quot;&gt;SCARA&lt;/Name&gt;
        ///    &lt;En type=&quot;stri [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string RobotType {
            get {
                return ResourceManager.GetString("RobotType", resourceCulture);
            }
        }
    }
}
